"use client"

import * as React from "react"
import { toast } from "sonner"

import { createProjectAction } from "@/actions/project"
import {
  initialCreateProjectState,
  type CreateProjectState,
} from "@/types/project"
import { Button, IconButton } from "@/components/ui/button"
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/components/ui/drawer"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { PlusIcon } from "@phosphor-icons/react"

// Create Project form. Only the fields a user supplies per insertProjectSchema
// are exposed: name (required) and template_id (optional). Everything else on
// the project row is generated by the server/DB. Submission runs the
// createProjectAction server action, which revalidates the projects page.
export function CreateProjectDrawer({
  buttonVariant = "default",
}: {
  buttonVariant?: "default" | "icon"
}) {
  const [open, setOpen] = React.useState(false)
  const [name, setName] = React.useState("")

  // Wrap the server action so the toast / close / reset run client-side right
  // after it resolves, instead of in an effect that reacts to state changes.
  const [state, formAction, isPending] = React.useActionState(
    async (prevState: CreateProjectState, formData: FormData) => {
      const result = await createProjectAction(prevState, formData)
      if (result.status === "success") {
        toast.success(result.message)
        setName("")
        setOpen(false)
      } else if (result.status === "error" && !result.fieldErrors) {
        toast.error(result.message)
      }
      return result
    },
    initialCreateProjectState
  )

  return (
    <Drawer open={open} onOpenChange={setOpen} swipeDirection="right">
      <DrawerTrigger
        render={
          buttonVariant === "icon" ? (
            <IconButton
              variant="secondary"
              size="icon"
              icon={PlusIcon}
              iconPosition="start"
              className="rounded-full pr-3"
              iconClassName="size-3"
            />
          ) : (
            <Button />
          )
        }
      >
        Create Project
      </DrawerTrigger>
      <DrawerContent className="w-[95vw] sm:w-[60vw] md:w-[50vw] lg:w-[40vw]">
        <form action={formAction} className="flex min-h-0 flex-1 flex-col">
          <DrawerHeader>
            <DrawerTitle className="text-xl font-light">
              {name || "Untitled"}
            </DrawerTitle>
            <DrawerDescription>
              Give your project a name to get started.
            </DrawerDescription>
          </DrawerHeader>

          <div className="flex-1 overflow-y-auto px-4 py-4">
            <FieldGroup>
              {/* name — required */}
              <Field data-invalid={!!state.fieldErrors?.name}>
                <FieldLabel htmlFor="project-name">
                  Project name <span className="text-destructive">*</span>
                </FieldLabel>
                <Input
                  id="project-name"
                  name="name"
                  placeholder="My awesome project"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  aria-invalid={!!state.fieldErrors?.name}
                  autoFocus
                />
                <FieldError>{state.fieldErrors?.name}</FieldError>
              </Field>

              {/* template_id — optional */}
              <Field data-invalid={!!state.fieldErrors?.template_id}>
                <FieldLabel htmlFor="project-template">Template ID</FieldLabel>
                <Input
                  id="project-template"
                  name="template_id"
                  placeholder="Optional template UUID"
                  aria-invalid={!!state.fieldErrors?.template_id}
                />
                <FieldDescription>
                  Leave blank to start from a blank project.
                </FieldDescription>
                <FieldError>{state.fieldErrors?.template_id}</FieldError>
              </Field>
            </FieldGroup>
          </div>

          <DrawerFooter className="flex-row justify-end">
            <DrawerClose render={<Button type="button" variant="outline" />}>
              Close
            </DrawerClose>
            <Button type="submit" disabled={isPending}>
              {isPending ? "Creating…" : "Create Project"}
            </Button>
          </DrawerFooter>
        </form>
      </DrawerContent>
    </Drawer>
  )
}
